### ISSUE TITLE
Add decoder for ndjson in to inventory.go

### ISSUE THREAD

**Issue by arsenyspb** [williamchanrico/planet-exporter#10]
**As A** solution architect
**I Need To** support new-line delimited JSON (ndjson) as input
**So That** I can integrate tooling directly with Planet Exporter

**Context:**

Currently, JSON decoder in [inventory.go](https://github.com/williamchanrico/planet-exporter/blob/9a7773f2590f1e1fa79e368f7bb5de59a9f33bf4/collector/task/inventory/inventory.go#L117) goes over the HTTP response at once, and therefore only supports a comma-separated JSON with structure similar to:

```
[ { "ip_address": "10.1.2.3","domain": "xyz.service.consul","hostgroup": "xyz"},{"ip_address": "10.2.3.4","domain":"debugapp.service.consul","hostgroup": "debugapp"}]
```

**Change required:**

Since modern scale-out Data Warehouses and RDBMS solutions default to [ndjson](http://ndjson.org/) for export, e.g. BigQuery export [DestinationFormat](https://googleapis.dev/python/bigquery/latest/_modules/google/cloud/bigquery/enums.html#DestinationFormat), support the NDJSON, and use Decoder to go over response line by line, until the `Decoder.More()` is FALSE ([reference](https://pkg.go.dev/encoding/json#Decoder.More)), to support structure similar to:

```
{"ip_address": "10.1.2.3","domain": "xyz.service.consul","hostgroup": "xyz"}
{"ip_address": "10.2.3.4","domain":"debugapp.service.consul","hostgroup": "debugapp"}
```

**User value:**

Simplified deployment when service naming is defined in pipeline of transformations in Data Warehouses / RDBMS, and uses its standard export tooling.

**Non-functional requirements:**

- Define parametric formats by e.g. `-task-inventory-format [jsonarray,ndjson]` to open path for future possible implementations of `csv`, `avro` and etc?
- Does `Unmarshal` play any role? I guess no.

**Comment by williamchanrico** [comment]
Thanks @arsenyspb
With current implementation, supporting other formats is simple and I agree that it would add a good value.
I can submit a PR for this.

**Comment by williamchanrico** [comment]
[planet-exporter-v0.2.0-rc.2](https://github.com/williamchanrico/planet-exporter/releases)
