### ISSUE TITLE
"Too many pages open" with taskEbpfEnabled=true

### ISSUE THREAD

**Issue by maitreya-source** [williamchanrico/planet-exporter#8]
If PE is kept running for more than 45 mins with EBPF scrapper enabled, it throws "too many pages open" errors.

**Comment by maitreya-source** [comment]
**Troubleshooting**

* [netstat -anp] - can see multiple connections ESTABLISHED to :9345.
  * This basically means connections to :9435 (ebpf) are not getting closed. 

* PE is just initialising the transport, not http connection itself : [prometheus/prometheus.go#L34](https://github.com/williamchanrico/planet-exporter/blob/master/pkg/prometheus/prometheus.go#L34)

* We are calling [prom2json](https://github.com/prometheus/prom2json), which is establishing the connection: [prom2json/prom2json.go at master · prometheus/prom2json · GitHub](https://github.com/prometheus/prom2json/blob/master/prom2json.go#L159), but I also see it's being closed there. 

* PE is establishing a new transport every 7 seconds  
   * [Transport definition](https://github.com/williamchanrico/planet-exporter/blob/master/pkg/prometheus/prometheus.go#L34). 
   * prometheus.Scrape is being called in loop.
   
**Possible solutions**

* We can restart the service every 30 mins or so.
* We can reuse the same transport: https://stackoverflow.com/questions/17948827/reusing-http-connections-in-go.

**Comment by maitreya-source** [comment]
I have a PR ready to go in once EBPF [PR#7](https://github.com/williamchanrico/planet-exporter/pull/7) is submitted with changes to reuse the same transport.

**Comment by williamchanrico** [comment]
Ah yes, I have seen similar versions of this http.Transport misuse behavior in other projects.

Besides the http.Transport getting created on every Scrape function call,
the makeTransport() is removing several [default values](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/net/http/transport.go;l=43-54
) that we should just keep.

Thanks for raising this and the comprehensive summary!

**Comment by williamchanrico** [comment]
Hi @maitreya-source I have submitted [PR#9](https://github.com/williamchanrico/planet-exporter/pull/9) to fix this and triggered a release candidate.
